//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MHKIM_BILL_DBEntities : DbContext
    {
        public MHKIM_BILL_DBEntities()
            : base("name=MHKIM_BILL_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TAcctCashMst> TAcctCashMst { get; set; }
        public virtual DbSet<TAcctMst> TAcctMst { get; set; }
        public virtual DbSet<TCashAttrGame> TCashAttrGame { get; set; }
        public virtual DbSet<TCashAttrHist> TCashAttrHist { get; set; }
        public virtual DbSet<TCashAttrMgmt> TCashAttrMgmt { get; set; }
        public virtual DbSet<TCashMst> TCashMst { get; set; }
        public virtual DbSet<TCashReceiptMst> TCashReceiptMst { get; set; }
        public virtual DbSet<TCashUseDtl> TCashUseDtl { get; set; }
        public virtual DbSet<TPayIncompleteMst> TPayIncompleteMst { get; set; }
        public virtual DbSet<TPayNotiMgmt> TPayNotiMgmt { get; set; }
        public virtual DbSet<TPayToolMgmt> TPayToolMgmt { get; set; }
        public virtual DbSet<TPGHist> TPGHist { get; set; }
        public virtual DbSet<TPGMgmt> TPGMgmt { get; set; }
        public virtual DbSet<TPGPayAmtHist> TPGPayAmtHist { get; set; }
        public virtual DbSet<TPGPayAmtMgmt> TPGPayAmtMgmt { get; set; }
        public virtual DbSet<TPGPayLogMst> TPGPayLogMst { get; set; }
        public virtual DbSet<TPGServiceCountryMgmt> TPGServiceCountryMgmt { get; set; }
        public virtual DbSet<TSiteCodeMgmt> TSiteCodeMgmt { get; set; }
    }
}
