//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPGPayLogMst
    {
        public long OrderNo { get; set; }
        public int SeqNo { get; set; }
        public byte SiteCode { get; set; }
        public int UserNo { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<long> MstUserNo { get; set; }
        public Nullable<byte> GenderCode { get; set; }
        public Nullable<System.DateTime> BirthDay { get; set; }
        public string EmailAddr { get; set; }
        public string CountryCode { get; set; }
        public Nullable<System.DateTime> MemberRegDate { get; set; }
        public string GameCode { get; set; }
        public byte PayToolCode { get; set; }
        public string PGCode { get; set; }
        public string MallID { get; set; }
        public string CurrencyCode { get; set; }
        public decimal PayAmt { get; set; }
        public decimal VATAmt { get; set; }
        public string TID { get; set; }
        public System.DateTime PayYMD { get; set; }
        public string ReserveData { get; set; }
        public string PayRsltCode { get; set; }
        public string PayRsltMsg { get; set; }
        public string IPAddr { get; set; }
        public string AccessCountryCode { get; set; }
        public byte StateCode { get; set; }
        public System.DateTime RegDate { get; set; }
        public Nullable<System.DateTime> UpdDate { get; set; }
    }
}
