//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PGproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TPGPayAmtHist
    {
        public int SeqNo { get; set; }
        public byte SiteCode { get; set; }
        public string GameCode { get; set; }
        public byte PayToolCode { get; set; }
        public string PGCode { get; set; }
        public string MallID { get; set; }
        public string CurrencyCode { get; set; }
        public decimal PayAmt { get; set; }
        public short DisplaySort { get; set; }
        public string DisplayTitle { get; set; }
        public decimal RealCashAmt { get; set; }
        public string BonusCashPayFlag { get; set; }
        public string CashAttrCode { get; set; }
        public Nullable<byte> BonusCashPayTypeCode { get; set; }
        public Nullable<decimal> BonusCashAmt { get; set; }
        public string UseFlag { get; set; }
        public string AdminID { get; set; }
        public System.DateTime RegDate { get; set; }
    }
}
